Fixed: AttributeError: 'UserSetting' object has no attribute 'module' in xaquakesounds.py Fixed: TypeError: iteration over non-sequence in xaquakesounds.py Fixed: ValueError: Popuplib: Cannot delete popup Easymenu("xamainconfigmenu"), it does not exist in xaquakesounds.py